# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run './initialise.py'

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(f'Version: {np.__version__}')
print('Config:')
np.show_config()

Version: 1.24.3
Config:
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
accelerate_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_info:
    libraries = ['cblas', 'blas', 'blas']
    library_dirs = ['/usr/lib64']
    include_dirs = ['/usr/local/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'blas']
    library_dirs = ['/usr/lib64']
    include_dirs = ['/usr/local/include']
    language = c
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
flame_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_thread

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [6]:
v = np.zeros(10)
print(f"{v.size * v.itemsize} B")

80 B


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [11]:
!python3 -c `import numpy; numpy.info(numpy.add)`

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [14]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [17]:
v = np.zeros(10)
v[4] = 1
v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [16]:
v = np.arange(10, 59)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [18]:
v[::-1]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [19]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [20]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [22]:
np.random.random((3,3,3))

array([[[0.73704011, 0.58067429, 0.95093309],
        [0.65367737, 0.74201415, 0.98150139],
        [0.57018849, 0.30233983, 0.33167857]],

       [[0.4563723 , 0.27647823, 0.39444012],
        [0.84922295, 0.93235406, 0.63898883],
        [0.08713589, 0.70399402, 0.60258158]],

       [[0.95942506, 0.33174019, 0.59346288],
        [0.09088884, 0.26507194, 0.52325804],
        [0.14418485, 0.39321849, 0.75411709]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [27]:
m = np.random.random((10,10))
f"{m.min()=} {m.max()=}"

'm.min()=0.0009618446775485623 m.max()=0.983202624351314'

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [28]:
np.random.random(30).mean()

0.5450221619072209

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [32]:
m = np.ones((10,10))
m[1:-1,1:-1] = 0
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [33]:
np.pad(m, pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [35]:
(
    0 * np.nan,
    np.nan == np.nan,
    np.inf > np.nan,
    np.nan - np.nan,
    np.nan in set([np.nan]),
    0.3 == 3 * 0.1,
)

(nan, False, False, nan, True, False)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [37]:
np.diag(np.arange(1, 5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [40]:
v = np.zeros((8,8))
v[::2, ::2] = 1
v[1::2, 1::2] = 1
v

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [41]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [44]:
np.tile(
    np.array([
        [1, 0], 
        [0, 1]
    ]), 
    (4, 4)
)

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [45]:
m = np.random.random((5,5))
(m - np.mean(m)) / np.std(m)

array([[-1.3569801 ,  0.41306057, -0.01387643, -0.03072543,  0.81727538],
       [-0.61399211,  1.60671383, -1.43250818,  0.51213991, -1.05586529],
       [ 0.66324821,  0.71686744, -0.64512302, -1.4380494 ,  0.74598781],
       [-1.91149181, -1.82438349,  0.57024433,  0.68964017,  1.18091925],
       [ 0.40326522,  0.92058339,  0.91590672,  0.75298652, -0.58584348]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [46]:
np.dtype([
    ("r", np.ubyte),
    ("g", np.ubyte),
    ("b", np.ubyte),
    ("a", np.ubyte)
])

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [48]:
np.ones((5, 3)) @ np.ones((3, 2))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [51]:
v = np.arange(1, 11)
v[(3 < v) & (v < 8)] *= -1
v

array([ 1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [52]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [61]:
Z = np.arange(0, 10)
(
    Z**Z,
    2 << Z >> 2,
    Z <- Z,
    1j * Z,
    Z / 1 / 1,
)


(array([        1,         1,         4,        27,       256,      3125,
            46656,    823543,  16777216, 387420489]),
 array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256]),
 array([False, False, False, False, False, False, False, False, False,
        False]),
 array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j,
        0.+8.j, 0.+9.j]),
 array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [62]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_1422122/548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipykernel_1422122/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/tmp/ipykernel_1422122/548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [67]:
v = np.random.random((5)) * 5
np.where(v > 0, np.ceil(v), np.floor(v))

array([2., 2., 1., 2., 3.])

#### 30. How to find common values between two arrays? (★☆☆)

In [74]:
v1 = np.random.randint(0, 20, 20)
v2 = np.random.randint(0, 20, 20)
print(np.intersect1d(v1,v2))

[ 5  9 14 16 17 19]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [77]:
with np.errstate(all="ignore"):
    ...

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [78]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_1422122/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [83]:
dates = (
    np.datetime64('today') - np.timedelta64(1),
    np.datetime64('today'),
    np.datetime64('today') + np.timedelta64(1),
)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [84]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [87]:
A = np.ones(3) * 1
B = np.ones(3) * 2
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [88]:
v = np.random.uniform(0,10,10)

(
    v - v % 1,
    v // 1,
    np.floor(v),
    v.astype(int),
    np.trunc(v),
)

(array([9., 7., 1., 3., 2., 9., 1., 2., 1., 4.]),
 array([9., 7., 1., 3., 2., 9., 1., 2., 1., 4.]),
 array([9., 7., 1., 3., 2., 9., 1., 2., 1., 4.]),
 array([9, 7, 1, 3, 2, 9, 1, 2, 1, 4]),
 array([9., 7., 1., 3., 2., 9., 1., 2., 1., 4.]))

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [89]:
np.tile(np.arange(0, 5), (5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [92]:
def generate():
    for x in range(10):
        yield x
np.fromiter(generate(), dtype=int, count=-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [93]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [96]:
v = np.random.random(10)
v.sort()
v

array([0.06194971, 0.07060726, 0.16547386, 0.23581188, 0.46233096,
       0.56232683, 0.64436219, 0.7789807 , 0.84294586, 0.88938796])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [97]:
np.add.reduce(np.arange(10))

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [101]:
A = np.random.randint(0, 10, 5)
B = np.random.randint(0, 10, 5)
np.array_equal(A, B)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [100]:
v = np.zeros(10)
v.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [102]:
m = np.random.random((10, 2))
x, y = m[:, 0], m[:, 1]
r = np.sqrt(x**2 + y**2)
t = np.arctan2(y, x)
(r, t)

(array([1.30893943, 0.8535086 , 0.66073342, 0.62567523, 0.50435312,
        0.18582164, 0.98573959, 0.72561161, 0.55466863, 0.7595571 ]),
 array([0.83714531, 0.91146642, 1.05415603, 1.11643914, 1.45993874,
        0.80153304, 0.46392143, 1.54043406, 0.4904559 , 0.35428194]))

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [103]:
v = np.random.random(10)
v[v.argmax()] = 0

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [104]:
v = np.zeros(
    (5, 5), 
    [
        ('x', float),
        ('y', float)
    ]
)
v['x'], v['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [106]:
x = np.arange(5)
y = x + 0.5
1.0 / np.subtract.outer(x, y)

array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222],
       [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [108]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [109]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [111]:
v = np.arange(100)
s = np.random.uniform(0,100)
v[np.abs(v - s).argmin()]

3

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [113]:
np.zeros(10, [
    ('position', 
     [
         ('x', float, 1),
         ('y', float, 1)
     ]),
    ('color',
     [
         ('r', float, 1),
         ('g', float, 1),
         ('b', float, 1)
     ])
])

/tmp/ipykernel_1422122/2125553789.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np.zeros(10, [


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [117]:
v = np.random.random((100,2))
x, y = np.atleast_2d(v[:, 0], v[:, 1])
np.sqrt((x - x.T)**2 + (y - y.T)**2)

array([[0.        , 0.51041421, 0.35297252, ..., 0.28304842, 0.30513967,
        0.62029282],
       [0.51041421, 0.        , 0.78763608, ..., 0.63753292, 0.51977095,
        0.468661  ],
       [0.35297252, 0.78763608, 0.        , ..., 0.56777048, 0.64232541,
        0.67525635],
       ...,
       [0.28304842, 0.63753292, 0.56777048, ..., 0.        , 0.14738375,
        0.87851321],
       [0.30513967, 0.51977095, 0.64232541, ..., 0.14738375, 0.        ,
        0.8244425 ],
       [0.62029282, 0.468661  , 0.67525635, ..., 0.87851321, 0.8244425 ,
        0.        ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [122]:
v = (np.random.rand(10)).astype(np.float32)
v = v.view(np.int32)
v

array([1062158720, 1060077721, 1037044073, 1056991965, 1058803599,
       1061780328, 1061719341, 1056384255, 1051240114, 1062897057],
      dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
np.genfromtxt(file, delimiter=",", dtype=np.int)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [123]:
np.info(np.ndenumerate)

 ndenumerate(arr)

Multidimensional index iterator.

Return an iterator yielding pairs of array coordinates and values.

Parameters
----------
arr : ndarray
  Input array.

See Also
--------
ndindex, flatiter

Examples
--------
>>> a = np.array([[1, 2], [3, 4]])
>>> for index, x in np.ndenumerate(a):
...     print(index, x)
(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [125]:
x, y = np.meshgrid(np.linspace(-1, 1, 5), 
                   np.linspace(-1, 1, 5))
z = np.sqrt(x**2 + y**2)
np.exp(-z**2)

array([[0.13533528, 0.2865048 , 0.36787944, 0.2865048 , 0.13533528],
       [0.2865048 , 0.60653066, 0.77880078, 0.60653066, 0.2865048 ],
       [0.36787944, 0.77880078, 1.        , 0.77880078, 0.36787944],
       [0.2865048 , 0.60653066, 0.77880078, 0.60653066, 0.2865048 ],
       [0.13533528, 0.2865048 , 0.36787944, 0.2865048 , 0.13533528]])

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [129]:
p = 5
m = np.zeros((5,5))
np.put(m, np.random.choice(range(25), p, replace=False), 10)
m

array([[ 0.,  0.,  0.,  0.,  0.],
       [10.,  0.,  0., 10.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [10.,  0., 10., 10.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [131]:
m = np.random.rand(5, 10)
m - m.mean(axis=1, keepdims=True)

array([[ 0.08285531, -0.35725971,  0.19397703,  0.19025353, -0.01969111,
         0.31891035,  0.13296913, -0.32141025, -0.10347449, -0.1171298 ],
       [-0.21953422, -0.21098511,  0.39218207,  0.47535153,  0.09519794,
        -0.18187301, -0.34342037,  0.5204161 , -0.40888807, -0.11844687],
       [ 0.03207352, -0.10850493,  0.05910407, -0.17557089, -0.20635936,
         0.27114616,  0.32678683, -0.03003602, -0.11541465, -0.05322473],
       [ 0.49518156, -0.22487203,  0.04584989, -0.18313412,  0.31953357,
         0.17802844, -0.25091791,  0.00938418, -0.12112113, -0.26793246],
       [-0.24785099,  0.12344078, -0.13010645,  0.17732374,  0.16389237,
         0.08792642,  0.37291036, -0.02009486, -0.19054549, -0.33689589]])

#### 59. How to sort an array by the nth column? (★★☆)

In [133]:
n = 0
m = np.random.randint(0, 10, (3, 3))
m[m[:, n].argsort()]

array([[2, 5, 0],
       [6, 5, 5],
       [7, 4, 8]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [140]:
m = np.ones((5, 5))
m[:, 1] = np.nan
any(np.isnan(m).all(axis=0))

True

#### 61. Find the nearest value from a given value in an array (★★☆)

In [141]:
x = 1
v = np.random.uniform(0, 1, 8)
v.flat[np.abs(v - x).argmin()]

0.9177576201075951

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [142]:
A = np.arange(3).reshape(3, 1)
B = np.arange(3).reshape(1, 3)
it = np.nditer([A, B, None])
for x, y, z in it: 
    z[...] = x + y
it.operands[2]

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

#### 63. Create an array class that has a name attribute (★★☆)

In [149]:
class MyArray(np.ndarray):
    def __new__(cls, arr, name="unnamed"):
        obj = np.asarray(arr).view(cls)
        obj.name = name
        return obj
        
    def __finalize__(self, x):
        if x is None:
            return
        self.info = getattr(x, 'name', "unnamed")
        
MyArray(np.ones(5).astype(int32), str('five_ones')).name

'five_ones'

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [151]:
v = np.ones(8)
i = np.random.randint(0, len(v), 5)
v += np.bincount(i, minlength=len(v))
v

array([2., 1., 1., 3., 2., 1., 2., 1.])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [153]:
x = [1, 2, 3, 4, 5, 6]
i = [1, 3, 9, 3, 4, 1]
np.bincount(i, x)

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [161]:
w, h = 64, 64
i = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
len(np.unique(i))

4

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [162]:
a = np.random.randint(0, 32, (3, 3, 3, 3))
a.sum(axis=(-2, -1))

array([[136, 139, 121],
       [155, 198, 216],
       [128, 136,  60]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [163]:
D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)
np.bincount(S, weights=D) / np.bincount(S)

array([0.61507872, 0.44030128, 0.53562686, 0.46528738, 0.5367008 ,
       0.55346212, 0.4748132 , 0.58683823, 0.52834314, 0.49426676])

#### 69. How to get the diagonal of a dot product? (★★★)

In [164]:
x = np.random.uniform(0, 1, (3, 3))
y = np.random.uniform(0, 1, (3, 3))
np.sum(x * y.T, axis=1)

array([0.77349218, 0.79922712, 0.94869919])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [165]:
v = np.array([1, 2, 3, 4, 5])
z = np.zeros(len(v) + (len(v) - 1) * 3)
z[::4] = v
z

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [166]:
a = np.ones((5, 5, 3))
b = 2 * np.ones((5, 5))
a * b[:, :, None]

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

#### 72. How to swap two rows of an array? (★★★)

In [167]:
m = np.ones((3,3))
m[[0,1]] = m[[1,0]]

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [170]:
faces = np.random.randint(0, 10, (10, 3))
x = np.roll(faces.repeat(2, axis=1), -1, axis=1)
x = x.reshape(len(x) * 3, 2)
x = np.sort(x, axis=1)
y = x.view(dtype=[('p0', x.dtype), ('p1',x.dtype)] )
np.unique(y)

array([(0, 1), (0, 3), (0, 5), (0, 6), (0, 7), (0, 9), (1, 1), (2, 2),
       (2, 3), (2, 4), (2, 5), (2, 7), (2, 8), (3, 4), (3, 7), (4, 7),
       (4, 9), (5, 6), (5, 7), (6, 9), (7, 9), (9, 9)],
      dtype=[('p0', '<i8'), ('p1', '<i8')])

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [171]:
C = np.bincount([1, 2, 3, 4, 5, 6])
A = np.repeat(np.arange(len(C)), C)
A

array([1, 2, 3, 4, 5, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [172]:
n = 3
v = np.arange(10)
r = np.cumsum(v, dtype=float)
r[n:] = r[n:] - r[:-n]
r[n - 1:] / n

array([1., 2., 3., 4., 5., 6., 7., 8.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [173]:
from numpy.lib import stride_tricks

a = np.arange(10)
window = 3
shape = (a.size - window + 1, window)
strides = (a.strides[0], a.strides[0])
stride_tricks.as_strided(a, shape=shape, strides=strides)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [176]:
v1 = np.random.uniform(-1.0, 1.0, 10)
v2 = np.random.randint(0, 2, 10)
(
    np.negative(v1, out=v1),
    np.logical_not(v2, out=v2),
)

(array([ 0.27233274,  0.42175015,  0.65772885, -0.30456761, -0.20935605,
        -0.23810214,  0.37625387,  0.98848083,  0.11462637, -0.23236377]),
 array([0, 1, 1, 0, 1, 1, 1, 0, 1, 1]))

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [182]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
distance(P0, P1, p)

array([6.68485696, 7.98894169, 2.17074042, 5.52019041, 0.02160817,
       7.19001246, 2.49613697, 9.11318069, 0.09860477, 0.42282348])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [183]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[5.37826925e+00 1.13247454e+01 6.79346766e+00 7.02941510e+00
  3.99122106e+00 5.81272772e+00 1.09923594e+00 4.96256567e+00
  1.19804858e+01 7.85296164e-01]
 [1.10865040e+01 1.48252482e+01 1.42829095e+01 9.49052982e+00
  9.68672542e+00 5.18881603e+00 8.87048438e+00 9.97323440e+00
  1.70007717e+01 5.69359430e+00]
 [5.34962471e+00 1.10623025e+01 7.36089852e+00 6.67983752e+00
  3.96095844e+00 5.26429157e+00 1.58445510e+00 4.85087204e+00
  1.18698677e+01 1.32479438e-01]
 [1.86231647e+00 1.27363402e+00 1.11563159e+01 3.81933433e+00
  3.27175593e+00 6.03403799e+00 3.25329734e+00 3.37632248e+00
  3.65514913e+00 6.69965078e+00]
 [1.93303499e+00 8.39384405e+00 4.29457973e+00 4.41729075e+00
  5.48050734e-01 4.34645984e+00 1.83968941e+00 1.64918144e+00
  8.66505187e+00 2.40592192e+00]
 [3.17277454e+00 8.40824328e-01 8.52078041e+00 3.87368382e+00
  4.57674448e+00 5.05557790e+00 6.75416704e-01 4.39557781e+00
  2.63198418e+00 4.17449180e+00]
 [2.62475294e+00 5.78036714e+00 1.27072528e+01 5.32266749e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [184]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

#### 82. Compute a matrix rank (★★★)

In [185]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
rank

10

#### 83. How to find the most frequent value in an array?

In [186]:
Z = np.random.randint(0,10,50)
np.bincount(Z).argmax()

5

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [187]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
C

array([[[[1, 1, 4],
         [0, 4, 0],
         [4, 2, 1]],

        [[1, 4, 4],
         [4, 0, 3],
         [2, 1, 2]],

        [[4, 4, 2],
         [0, 3, 4],
         [1, 2, 4]],

        [[4, 2, 0],
         [3, 4, 3],
         [2, 4, 1]],

        [[2, 0, 1],
         [4, 3, 0],
         [4, 1, 1]],

        [[0, 1, 4],
         [3, 0, 2],
         [1, 1, 0]],

        [[1, 4, 4],
         [0, 2, 3],
         [1, 0, 2]],

        [[4, 4, 3],
         [2, 3, 1],
         [0, 2, 4]]],


       [[[0, 4, 0],
         [4, 2, 1],
         [2, 0, 3]],

        [[4, 0, 3],
         [2, 1, 2],
         [0, 3, 2]],

        [[0, 3, 4],
         [1, 2, 4],
         [3, 2, 1]],

        [[3, 4, 3],
         [2, 4, 1],
         [2, 1, 4]],

        [[4, 3, 0],
         [4, 1, 1],
         [1, 4, 3]],

        [[3, 0, 2],
         [1, 1, 0],
         [4, 3, 3]],

        [[0, 2, 3],
         [1, 0, 2],
         [3, 3, 4]],

        [[2, 3, 1],
         [0, 2, 4],
         [3, 4, 3]]],


    

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [188]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
S

Symetric([[ 9,  8,  4,  5,  8],
          [ 8,  7,  5,  5, 12],
          [ 4,  5,  0, 42,  3],
          [ 5,  5, 42,  5,  9],
          [ 8, 12,  3,  9,  7]])

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [189]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
S

array([[200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [191]:
Z = np.ones((16,16))
k = 4
windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))
S

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [195]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(10, 10))
for i in range(100): 
    Z = iterate(Z)

#### 89. How to get the n largest values of an array (★★★)

In [196]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
Z[np.argsort(Z)[-n:]]

array([9995, 9996, 9997, 9998, 9999])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [197]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix

cartesian(([1, 2, 3], [4, 5], [6, 7]))

array([[1, 4, 6],
       [1, 4, 7],
       [1, 5, 6],
       [1, 5, 7],
       [2, 4, 6],
       [2, 4, 7],
       [2, 5, 6],
       [2, 5, 7],
       [3, 4, 6],
       [3, 4, 7],
       [3, 5, 6],
       [3, 5, 7]])

#### 91. How to create a record array from a regular array? (★★★)

In [198]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
R

rec.array([(b'Hello', 2.5, 3), (b'World', 3.6, 2)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [199]:
x = np.random.rand(int(5e7))

(
    np.power(x,3),
    x*x*x,
    np.einsum('i,i,i->i',x,x,x),
)

(array([0.11395017, 0.29248194, 0.02095637, ..., 0.74688658, 0.24863519,
        0.74944299]),
 array([0.11395017, 0.29248194, 0.02095637, ..., 0.74688658, 0.24863519,
        0.74944299]),
 array([0.11395017, 0.29248194, 0.02095637, ..., 0.74688658, 0.24863519,
        0.74944299]))

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [200]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
np.where(C.any((3,1)).all(1))[0]

array([0, 2, 7])

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [201]:
Z = np.random.randint(0,5,(10,3))
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
U

array([[4, 0, 1],
       [2, 4, 4],
       [4, 3, 3],
       [3, 2, 4],
       [0, 2, 0],
       [1, 2, 1],
       [2, 4, 4],
       [4, 3, 0],
       [4, 1, 0]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [202]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
np.unpackbits(I[:, np.newaxis], axis=1)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [203]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
uZ

array([[0, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [204]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)
np.einsum('i,j->ij', A, B)

array([[0.39848774, 0.22155122, 0.36354927, 0.14375581, 0.22410641,
        0.38470819, 0.19517063, 0.01528993, 0.49755952, 0.34846148],
       [0.59321867, 0.32981773, 0.54120665, 0.21400566, 0.33362157,
        0.5727054 , 0.2905456 , 0.02276174, 0.74070434, 0.51874584],
       [0.06106266, 0.03394962, 0.05570883, 0.02202856, 0.03434117,
        0.05895114, 0.02990716, 0.00234297, 0.07624402, 0.05339684],
       [0.54681931, 0.30402061, 0.49887548, 0.19726693, 0.30752693,
        0.52791051, 0.26782021, 0.0209814 , 0.6827692 , 0.47817147],
       [0.24952137, 0.1387289 , 0.22764392, 0.09001568, 0.14032888,
        0.24089302, 0.12221014, 0.00957411, 0.31155722, 0.21819639],
       [0.42204852, 0.23465055, 0.3850443 , 0.15225544, 0.23735681,
        0.40745425, 0.20671019, 0.01619396, 0.52697798, 0.36906444],
       [0.4563681 , 0.25373155, 0.41635482, 0.16463635, 0.25665787,
        0.44058707, 0.22351917, 0.0175108 , 0.56983007, 0.39907553],
       [0.45152304, 0.25103779, 0.4119345

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [205]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [206]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [208]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.20174643  0.20983531]
